app/apps/loans/urls.py
from django.urls import path
from apps.loans import views
from apps.loans.views import LoanListView, LoanDeleteView, LoanUpdateView

urlpatterns = [
    path('', views.home, name='home'),
    path('loans/', views.loans, name='loans'),
    path('loans/create/', views.create_loan, name='loans_create'),
    path('loans/<int:loan_id>', views.loan_detail, name='loan_detail'),
    path('loans/<int:loan_id>/delete', views.delete_loan, name='delete_loan'),

    path("loans/list", LoanListView.as_view(), name="loan_list"),
    path("loan/<int:pk>/delete/", LoanDeleteView.as_view(), name="loan_delete"),
    path("loan/<int:pk>/update/", LoanUpdateView.as_view(), name="loan_update"),
]

app/apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    path('signupp/', views.signupp, name='signupp'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.loans.urls')),
    path('', include('apps.profiles.urls')),
]

app/apps/loans/models.py
from django.db import models
from apps.loans.constants import GENDER_CHOICES, STATUS_CHOICES
from django.core.validators import RegexValidator

dni_validator = RegexValidator(
    regex=r"^\d{8}$",
    message="El DNI debe contener 8 dígitos numéricos.",
)

class Loan(models.Model):
    """
        Model representing a loan application.

        Base model for other models in the project, providing common attributes:
            + dni (IntegerField): Unique identifier for the loan applicant (validated using dni_validator).
            + first_name (CharField): First name of the loan applicant.
            + last_name (CharField): Last name of the loan applicant.
            + gender (CharField): Gender of the loan applicant (choices defined in GENDER_CHOICES).
            + email (EmailField): Email address of the loan applicant.
            + amount (DecimalField): Amount requested in the loan application.
            + created_at (DateTimeField): Timestamp indicating when the loan application was created.
            + status (IntegerField): Status of the loan application (choices defined in STATUS_CHOICES).

        Methods:
            + __str__: String representation of the loan, showing DNI and full name.
            + status_display: Human-readable display of the loan status.

        Meta:
            + app_label: Specifies the app label for the model (loans).
    """
    dni = models.IntegerField(
        validators=[dni_validator],
        null=False,
        blank=False,
        db_index=True,
        unique=True,
    )
    first_name = models.CharField(max_length=100, null=False, blank=False)
    last_name = models.CharField(max_length=100, null=False, blank=False)
    gender = models.CharField(
        max_length=1, choices=GENDER_CHOICES, null=False, blank=False
    )
    email = models.EmailField(null=False, blank=False)
    amount = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, blank=False
    )
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS_CHOICES)
    
    class Meta:
        app_label = 'loans'

    def __str__(self):
        return f"{self.dni}-{self.first_name} {self.last_name}"
    
    def status_display(self):
        for value, label in STATUS_CHOICES:
            if value == self.status:
                return label

app/apps/loans/forms.py
from apps.loans.models import Loan
from django import forms

class LoanForm(forms.ModelForm):
    class Meta:
        model = Loan
        fields = ['first_name', 'last_name','dni','email', 'gender', 'amount']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'dni': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'gender': forms.TextInput(attrs={'class': 'form-control'}),
            'amount': forms.TextInput(attrs={'class': 'form-control'}),
        }

app/apps/loans/views.py
from django.shortcuts import render, redirect, get_object_or_404
from apps.loans.models import Loan
from apps.loans.forms import LoanForm
import requests
from django.contrib.auth.decorators import login_required
from django.conf import settings
from rest_framework import status
from django.views.generic import ListView, DeleteView, UpdateView
from django.urls import reverse_lazy
from apps.loans.constants import LOAN_APPROVE, STATUS_ACCEPTED, STATUS_REJECTED
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from serializers import LoanSerializer


def home(request):
    return render(request, 'home.html')


@login_required
def loans(request):
    loans = Loan.objects.all()

    return render(request, 'loans_list.html', {'loans' : loans})


def create_loan(request):
    """
        View for creating a loan application.

        This view handles both GET and POST requests:
        - GET: Renders the 'create_loan.html' template with an empty LoanForm.
        - POST: Processes the LoanForm submitted in the request.
        - Validates the form data.
        - Retrieves additional scoring information from an external API based on the provided DNI.
        - Updates the loan status based on the scoring results (approved or rejected).
        - Saves the loan application in the database.
        - Renders the 'create_loan.html' template with the form and a success/error message.

        Parameters:
        - request (HttpRequest): The HTTP request object.

        Returns:
        - HttpResponse: Rendered HTML response.
    """
    if request.method == 'GET':
        return render(request, 'create_loan.html', {
            'form': LoanForm()
        })
    elif request.method == 'POST':
        form = LoanForm(request.POST)
        if form.is_valid():        
            dni = form.cleaned_data.get('dni')
            api_url = '{}{}'.format(settings.URL_LOAD, dni)
            api_headers = {
            'credential': settings.CREDENTIAL
            }
            response = requests.get(api_url, headers=api_headers)
            if response.status_code == status.HTTP_200_OK:
                scoring_data = response.json()
                loan_state = scoring_data.get('status', False)
                new_loan = form.save(commit=False)

                if loan_state == LOAN_APPROVE:
                    new_loan.status = STATUS_ACCEPTED
                    message = 'El prestamo se creo con exito'

                else:
                    new_loan.status = STATUS_REJECTED
                    message = 'El usuario no es apto para el prestamo'

                new_loan.save()
                return render(request, 'create_loan.html', {
                    'form': form,
                    'error': message
                })
            else:
                return render(request, 'create_loan.html', {
                    'form': form,
                    'error': 'Error al consultar la API de scoring.'
                })
        else:
            return render(request, 'create_loan.html', {
                'form': form,
                'error': 'Por favor proporciona un dato válido'
            })


def loan_detail(request, loan_id):
    if request.method == 'GET':
        loan = get_object_or_404(Loan, pk=loan_id, loan_profile=request.user)
        form = LoanForm(instance=loan)
        return render(request, 'loan_detail.html', {'loan': loan, 'form': form})
    else:
        try:
            loan = get_object_or_404(Loan, pk=loan_id, loan_profile=request.user)
            form = LoanForm(request.POST, instance=loan)
            form.save()
            return redirect('loans')
        except ValueError:
            return render(request, 'loan_detail.html', {'loan': loan, 'form': form,
            'error' : "Error al actualizar el prestamo"})


def delete_loan(request, loan_id):
    loan = get_object_or_404(Loan, pk=loan_id, loan_profile=request.user)
    if request.method == 'POST':
        loan.delete()
        return redirect('loans')
    
@method_decorator(user_passes_test(lambda u: u.is_superuser), name='dispatch')
class LoanListView(ListView):
    model = Loan
    template_name = "loan_list.html"
    context_object_name = "loans"

class LoanDeleteView(DeleteView):
    model = Loan
    template_name = "loan_delete.html"
    success_url = reverse_lazy("loan_list")

class LoanUpdateView(UpdateView):
    model = Loan
    template_name = "loan_update.html"
    form_class = LoanForm
    success_url = reverse_lazy("loan_list")

app/apps/loans/templates/partials/about.html
{% load static %}

<section id="about" class="container mt-5 border border-dark p-4">
    <div class="row">
        <div class="col-md-12">
            <h2>Quienes somos?</h2>
            <p>En "Soy Moni", somos más que una aplicación, somos una comunidad que se preocupa por tu bienestar financiero. Nuestra misión es brindarte acceso a soluciones de préstamos y asesoramiento financiero de manera sencilla y segura.

                Con años de experiencia en el mundo financiero, entendemos las necesidades de las personas y sabemos que cada situación es única. Estamos aquí para ofrecerte opciones flexibles y adaptadas a tus circunstancias.
                
                Nuestro equipo de expertos está comprometido en ayudarte a tomar decisiones informadas y responsables en tu vida financiera. Queremos que te sientas empoderado para alcanzar tus metas y sueños.
                
                En "Soy Moni," valoramos la transparencia, la confianza y la privacidad de nuestros usuarios. Tus datos personales son tratados con el mayor cuidado y seguridad.
                
                Únete a la familia "Soy Moni" y descubre cómo podemos ayudarte a construir un futuro financiero más sólido. Estamos aquí para ti en cada paso del camino.</p>
        </div>
    </div>
</section>

app/apps/loans/templates/partials/card.html
{% load static %}

<div class="card text-dark bg-ligth">
  <div class="card-body">
    <h5 class="card-title">Préstamos personales online al instante</h5>
    <p class="card-text">Te presto hasta $490.000 pesos y podés devolverme en 12 cuotas.
      Mis créditos son fáciles, rápidos y seguros. Pedime efectivo ya
      y te transfiero de forma urgente.</p>
    <p class="card-text"><small class="text-muted"></small></p>
  </div>
  <img src="{% static 'img/pedimeydevolveme.png'%}" class="card-img-bottom" alt="..." height="500px">
</div>

app/apps/loans/templates/partials/carousel.html
{% load static %}

<div class="container">
    <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
          <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{% static 'img/buenassoymoni.jpg'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5></h5>
              <p></p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/simuladorr.png'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5></h5>
              <p></p>
            </div>
          </div>
          <div class="carousel-item">
            <img src="{% static 'img/compraonline.png'%}" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
              <h5></h5>
              <p></p>
            </div>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

app/apps/loans/templates/partials/featured.html
{% load static %}

<div class="card text-center text-dark bg-light">
    <div class="card-header">
      
    </div>
    <div class="card-body">
      <h3 class="card-title">Prestamos personales</h3>
      <p class="card-text">Consulta por nuestros prestamos personales de manera online en unos simples pasos.</p>
      <a href="{% url 'loans_create' %}" class="btn btn-dark">Solicitar prestamo</a>
    </div>
    <div class="card-footer text-muted">
      
    </div>
</div>

app/apps/loans/templates/partials/footer.html
{% load static %}

<div class="container footer">
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark">
      <div class="col-md-4 d-flex align-items-center text-light">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
          <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"/></svg>
        </a>
        <span class="text-muted text-light">&copy; 2021 Company, Inc</span>
      </div>
  
      <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"/></svg></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
        <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      </ul>
    </footer>
  </div>

app/apps/loans/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="{% url 'home' %}"> <img src="{% static 'img/logo.svg'%}" alt="Logo" width="120" height="60"></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ms-auto">
        <a class="nav-link active fw-bolder" aria-current="page" href="{% url 'home' %}">Inicio</a>
        <a class="nav-link fw-bolder" href="{% url 'loans_create' %}">Solicitar prestamo</a>
        {% if user.is_authenticated and user.is_superuser %} 
        <a class="nav-link fw-bolder" href="{% url 'loan_list' %}">Listado de prestamos</a>
        {% else %}
        <a class="nav-link fw-bolder" href="{% url 'profiles:signupp' %}">Crear cuenta</a>
        <a class="nav-link fw-bolder" href="{% url 'profiles:signin' %}">Iniciar sesion</a>
        {% endif %}
        {% if user.is_authenticated %} 
        <a class="nav-link fw-bolder" href="{% url 'profiles:logout' %}">Cerrar sesion</a>
        {% endif %}
      </div>
    </div>
  </div>
</nav>